# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy
[ -x /usr/bin/clear ] && /usr/bin/clear

# kill running ssh agent
kill $SSH_AGENT_PID
