# Some useful aliases
alias mutt='mutt -F ~/.muttrc '
alias gcc='gcc -pedantic -Wall -W -Wextra -Wfloat-equal -Wpadded -Wshadow '\
'-Wunreachable-code -Winline -Wno-long-long -std=c99'

# clipboard interaction
alias xclip='xclip -sel clip'

# adding more colors by default
alias grep='grep --color=always'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias less='less -R'

# handy short aliases for commonly used commands
alias h='history'
alias j='jobs -l'

# safer rm that asks confirmation
alias rm='rm -i'

# ssh logins
alias alpha='ssh gbalats@alpha.cs.umass.edu '
alias omega='ssh gbalats@omega.cs.umass.edu '
alias lobo='ssh lobo@lobo.di.uoa.gr '

# The ubiquitous 'll': directories first, with alphanumeric sorting:
alias ll="ls -lhFv --group-directories-first"
alias lm='ll | less'       #  Pipe through 'less'
alias lr='ll -R'           #  Recursive ls.
alias la='ll -A'           #  Show hidden files.
